/**
 * Sequence 0 RedactionService — minimal but real redaction engine
 * used on the redact_then_egress (Approve-then-Egress) path.
 *
 * Deterministic regex-driven redaction with a versioned rule set so
 * every redacted payload links to a redaction_record row that
 * downstream tooling can replay and inspect.
 *
 * The preview is generated by masking the matched PII shapes with
 * irreversible tokens. The original content is never written to
 * audit. We only persist rule_version, before_hash, after_hash,
 * summary, and residual_risk.
 */
import * as crypto from 'crypto';
import type { DatabaseService } from './database-service';
import { OgraError, OgraErrorCode } from '../shared/errors';

export interface RedactionRecordInput {
  runId: string;
  modelCallId?: string;
  ruleSetId: string;
  ruleVersion: string;
  beforeText: string;
  classification: string;
  approvalId?: string;
}

export interface RedactionResult {
  /** Canonical redaction evidence row created for this preview. */
  recordId: string;
  redactedText: string;
  beforeHash: string;
  afterHash: string;
  matches: Array<{ rule: string; preview: string; index: number; length: number }>;
}

const DEFAULT_RULES: Array<{ name: string; pattern: RegExp; replacement: string }> = [
  { name: 'email', pattern: /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g, replacement: '[REDACTED_EMAIL]' },
  { name: 'phone_e164', pattern: /\+?\d{1,3}[-.\s]?\(?\d{1,4}\)?[-.\s]?\d{1,4}[-.\s]?\d{2,4}[-.\s]?\d{2,4}/g, replacement: '[REDACTED_PHONE]' },
  { name: 'us_ssn', pattern: /\b\d{3}-\d{2}-\d{4}\b/g, replacement: '[REDACTED_SSN]' },
  { name: 'credit_card_pan', pattern: /\b(?:\d[ -]*?){13,19}\b/g, replacement: '[REDACTED_PAN]' },
  { name: 'ip_address', pattern: /\b(?:\d{1,3}\.){3}\d{1,3}\b/g, replacement: '[REDACTED_IP]' },
  { name: 'aws_access_key', pattern: /\bAKIA[0-9A-Z]{16}\b/g, replacement: '[REDACTED_AWS_KEY]' },
  { name: 'bearer_token', pattern: /[Bb]earer\s+[A-Za-z0-9._-]{20,}/g, replacement: '[REDACTED_TOKEN]' },
  { name: 'private_key_block', pattern: /-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/g, replacement: '[REDACTED_PRIVATE_KEY]' },
];

const RULE_VERSION = 'r1.0.0';

function sha256(s: string): string {
  return crypto.createHash('sha256').update(s).digest('hex');
}

export class RedactionService {
  constructor(
    private db: DatabaseService,
    /** Stable id of the active redaction rule set. Defaults to a
     *  built-in id; renderer-readable through Data Safety Center. */
    private ruleSetId: string = 'builtin-core-v1',
  ) {}

  /**
   * Apply the deterministic built-in rule set to a payload and
   * persist a redaction_record row. Returns a sanitized preview that
   * may be shown in the UI / approval dialog; never the original.
   */
  redact(input: RedactionRecordInput): RedactionResult {
    if (typeof input.beforeText !== 'string') {
      throw new OgraError(OgraErrorCode.INVALID_ARGUMENT, 'beforeText must be a string');
    }
    const beforeHash = sha256(input.beforeText);
    let redacted = input.beforeText;
    const matches: RedactionResult['matches'] = [];
    for (const rule of DEFAULT_RULES) {
      redacted = redacted.replace(rule.pattern, (match, ...rest) => {
        const offsetStr = rest[rest.length - 2];
        const index = typeof offsetStr === 'number' ? offsetStr : -1;
        matches.push({ rule: rule.name, preview: match, index, length: match.length });
        return rule.replacement;
      });
    }
    // Sequence 0 §3.6 — Approve-then-Egress rule: when the
    // egress payload is classified Confidential, the redactor
    // ALWAYS rewrites the JSON shape so that `task` and
    // `contextBlock` no longer carry raw user content. The egress
    // preview only contains (a) a provenance header, (b) the
    // redacted contextBlock (which the redactor has applied regex
    // rules to), and (c) a fixed task placeholder. The original
    // task is NEVER forwarded across the wire; downstream callers
    // see only the placeholder + the redacted context.
    //
    // Implementation note: we keep the JSON parseable so callers
    // can still read structured fields. The provenance header is
    // recorded as an additional sibling `_redaction_provenance`
    // field rather than a free-form prefix, so `JSON.parse(...)`
    // recovers the full redacted state.
    let parsedPayload: any = null;
    try {
      parsedPayload = JSON.parse(redacted);
    } catch {
      parsedPayload = null;
    }
    if (parsedPayload && typeof parsedPayload === 'object'
      && ('task' in parsedPayload || 'contextBlock' in parsedPayload)) {
      const originalTask = typeof parsedPayload.task === 'string' ? parsedPayload.task : '';
      if (originalTask.length > 0 && originalTask !== '[REDACTED-task]') {
        matches.push({
          rule: 'task-redaction',
          preview: `[task ${originalTask.length} chars]`,
          index: 0,
          length: originalTask.length,
        });
        parsedPayload.task = '[REDACTED-task]';
      }
      // Carry the provenance on the JSON itself; HTTP and audit see
      // the same string. The `_meta` field is opaque to the model
      // adapter and tells Core which rule version produced this
      // preview.
      parsedPayload._redaction_provenance = `ogra/redaction@${input.ruleVersion ?? RULE_VERSION}`;
      redacted = JSON.stringify(parsedPayload);
      matches.unshift({
        rule: 'provenance-header',
        preview: '(none)',
        index: 0,
        length: redacted.length,
      });
    }
    const afterHash = sha256(redacted);

    // Persist the redaction row. Stub columns omitted; we record
    // what plan 02 §3.8.1 requires.
    const redactionRowId = `rd_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`;
    this.db.getRawDB().prepare(`
      INSERT INTO redaction_records
        (id, run_id, model_call_id, rule_version, rule_set_id,
         before_hash, after_hash, summary, residual_risk, approval_id, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      redactionRowId,
      input.runId,
      input.modelCallId ?? null,
      input.ruleVersion ?? RULE_VERSION,
      this.ruleSetId,
      beforeHash,
      afterHash,
      this.summarize(matches),
      this.residualRisk(matches, input.classification),
      input.approvalId ?? null,
      new Date().toISOString(),
    );

    return { recordId: redactionRowId, redactedText: redacted, beforeHash, afterHash, matches };
  }

  /** Bind the preview evidence produced while parking a run to its canonical approval. */
  linkApproval(recordId: string, approvalId: string): void {
    const changed = this.db.getRawDB().prepare(
      'UPDATE redaction_records SET approval_id = ? WHERE id = ?',
    ).run(approvalId, recordId);
    if (changed.changes !== 1) {
      throw new OgraError(OgraErrorCode.NOT_FOUND, 'Redaction record not found for approval binding');
    }
  }

  /**
   * Persist an egress_records row that binds the redacted payload
   * hash + rule version + approval to the model call.
   */
  recordEgress(input: {
    runId: string;
    modelCallId?: string;
    routeDecisionId?: string;
    approvalId?: string;
    egressMode: 'auto_redact' | 'log_and_proceed' | 'approve_then_egress';
    payloadHash: string;
    payloadSummary: string;
    redactionRuleVersion: string;
    payloadClassification: string;
  }): void {
    this.db.getRawDB().prepare(`
      INSERT INTO egress_records
        (id, run_id, model_call_id, route_decision_id, approval_id,
         egress_mode, payload_hash, payload_summary,
         redaction_rule_version, payload_classification, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      `egr_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`,
      input.runId,
      input.modelCallId ?? null,
      input.routeDecisionId ?? null,
      input.approvalId ?? null,
      input.egressMode,
      input.payloadHash,
      input.payloadSummary,
      input.redactionRuleVersion,
      input.payloadClassification,
      new Date().toISOString(),
    );
  }

  private summarize(matches: Array<{ rule: string }>): string {
    const counts: Record<string, number> = {};
    for (const m of matches) counts[m.rule] = (counts[m.rule] ?? 0) + 1;
    return Object.entries(counts).map(([k, v]) => `${k}x${v}`).join(',') || 'no matches';
  }

  private residualRisk(matches: Array<{ rule: string }>, classification: string): string {
    if (matches.length === 0) return 'none';
    if (classification === 'Confidential' || classification === 'Restricted') {
      return 'medium: redaction applied; recommend narrower rule set';
    }
    return 'low';
  }
}
