/** Stable error codes for Ogra IPC and service operations */
export enum OgraErrorCode {
  // General
  UNKNOWN = 'UNKNOWN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INTERNAL = 'INTERNAL',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',

  // Input validation
  INVALID_ARGUMENT = 'INVALID_ARGUMENT',
  MISSING_FIELD = 'MISSING_FIELD',
  INVALID_WORKSPACE_ID = 'INVALID_WORKSPACE_ID',
  INVALID_PROVIDER_ID = 'INVALID_PROVIDER_ID',
  INVALID_MODEL_ID = 'INVALID_MODEL_ID',
  INVALID_PATH = 'INVALID_PATH',

  // Permission & Security
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  IPC_CHANNEL_REJECTED = 'IPC_CHANNEL_REJECTED',
  WORKSPACE_MISMATCH = 'WORKSPACE_MISMATCH',
  PATH_TRAVERSAL_DETECTED = 'PATH_TRAVERSAL_DETECTED',
  SYMLINK_ESCAPE_DETECTED = 'SYMLINK_ESCAPE_DETECTED',
  SECRET_ACCESS_DENIED = 'SECRET_ACCESS_DENIED',

  // Policy & Routing
  POLICY_BLOCKED = 'POLICY_BLOCKED',
  ROUTE_BLOCKED = 'ROUTE_BLOCKED',
  CLOUD_CALL_DENIED = 'CLOUD_CALL_DENIED',
  NO_ACCEPTABLE_MODEL = 'NO_ACCEPTABLE_MODEL',
  APPROVAL_REQUIRED = 'APPROVAL_REQUIRED',
  REDACTION_REQUIRED = 'REDACTION_REQUIRED',

  // Storage
  DATABASE_ERROR = 'DATABASE_ERROR',
  MIGRATION_FAILED = 'MIGRATION_FAILED',
  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
  KNOWLEDGE_BASE_NOT_FOUND = 'KNOWLEDGE_BASE_NOT_FOUND',
  DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND',
  RUN_NOT_FOUND = 'RUN_NOT_FOUND',
  RUN_INVALID_STATE = 'RUN_INVALID_STATE',
  PROVIDER_NOT_FOUND = 'PROVIDER_NOT_FOUND',
  MODEL_NOT_FOUND = 'MODEL_NOT_FOUND',
  AUDIT_NOT_FOUND = 'AUDIT_NOT_FOUND',
  NOT_FOUND = 'NOT_FOUND',

  // Model & Adapter
  MODEL_UNAVAILABLE = 'MODEL_UNAVAILABLE',
  PROVIDER_UNREACHABLE = 'PROVIDER_UNREACHABLE',
  ADAPTER_ERROR = 'ADAPTER_ERROR',
  CONNECTION_TEST_FAILED = 'CONNECTION_TEST_FAILED',

  // Indexing
  INDEXING_FAILED = 'INDEXING_FAILED',
  INDEXING_CANCELLED = 'INDEXING_CANCELLED',
  UNSUPPORTED_FILE_TYPE = 'UNSUPPORTED_FILE_TYPE',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',

  // Cancellation & Timeout
  CANCELLED = 'CANCELLED',
  TIMEOUT = 'TIMEOUT',

  // Audit
  AUDIT_CHAIN_BROKEN = 'AUDIT_CHAIN_BROKEN',
  AUDIT_VERIFICATION_FAILED = 'AUDIT_VERIFICATION_FAILED',
}

export class OgraError extends Error {
  constructor(
    public readonly code: OgraErrorCode,
    message: string,
    public readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = 'OgraError';
  }

  toJSON(): Record<string, unknown> {
    return {
      code: this.code,
      message: this.message,
      details: this.details,
    };
  }
}
